DROP TABLE kayttajat CASCADE;
DROP TABLE raakaaineet CASCADE;
DROP TABLE reseptit CASCADE;
DROP TABLE kuvat CASCADE;
DROP TABLE kategoriat CASCADE;
DROP TABLE menut CASCADE;
DROP TABLE reseptin_raakaaineet CASCADE;